#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# galera documentation build configuration file, created by
# sphinx-quickstart on Sat Apr 20 12:00:55 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.todo', 'cloud_sptheme.ext.autodoc_sections', 'cloud_sptheme.ext.table_styling', 'sphinx.ext.imgmath']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
import datetime
copyright = "Copyright 2013 - %s, Codership Oy. All Rights Reserved." % datetime.datetime.now().year

project = 'Galera Cluster'

rst_epilog = '.. |site-copyright| replace:: %s' % copyright

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '3.x and 4.x'
# The full version, including alpha/beta/rc tags.
#release = '3.x'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------





# import Cloud
import cloud_sptheme as csp

html_theme_options = { "roottarget": "index" }

# set the theme path to point to cloud's theme data
html_theme_path = [csp.get_theme_dir()]

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# html_theme = 'default'
html_theme = 'cloud'






# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = "Galera Cluster Documentation"

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'logo.png'

html_style = 'codership.css'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'galeradoc'


# -- Options for LaTeX output --------------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
    #'papersize': 'letterpaper',
    "papersize": "letterpaper",

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '10pt',
    'releasename': 'Releases 3.x and 4.x',
    'date': ''
}
# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('documentation/index', 'galera.tex', 'Galera Cluster Documentation',
   'Codership Oy', 'sphinxmanual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = True

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'galera', 'Galera Documentation',
     ['Codership Oy'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'galera', 'Galera Documentation',
   'Codership Oy', 'galera', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'


# -- Redirecting HTML files that were moved or renamed. ------------------------
#

redirect_files = [
   ('detectingaslownode.html', 'kb/best/detecting-slow-node.html'),
   ('twonode.html', 'kb/best/two-node-clusters.html'),
   ('dealingwithmultimasterconflicts.html', 'kb/trouble/multi-master-conflicts.html'),
   ('clusterstallonalter.html', 'kb/trouble/stall-on-alter.html'),
   ('userchanges.html', 'kb/trouble/user-changes.html'),
   ('configuration.html', 'training/tutorials/configuration.html'),
   ('galerainstallation.html', 'training/tutorials/galera-installation.html'),
   ('gettingstarted.html', 'training/tutorials/getting-started.html'),
   ('restartingcluster.html', 'training/tutorials/restarting-cluster.html'),
   ('startingcluster.html', 'training/tutorials/starting-cluster.html'),
   ('testingcluster.html', 'training/tutorials/testing-cluster.html'),
   ('wsrep-configuration.html', 'training/tutorials/wsrep-configuration.html'),
   ('userguide.html', 'documentation/administration.html'),
   ('arbitrator.html', 'documentation/arbitrator.html'),
   ('architecture.html', 'documentation/architecture.html'),
   ('autoeviction.html', 'documentation/auto-eviction.html'),
   ('backingupthecluster.html', 'documentation/backup-cluster.html'),
   ('certificationbasedreplication.html', 'documentation/certification-based-replication.html'),
   ('containers.html', 'documentation/containers.html'),
   ('deploymentvariants.html', 'documentation/deployment-variants.html'),
   ('deployment.html', 'documentation/deployment.html'),
   ('limitations.html', 'documentation/differences.html'),
   ('docker.html', 'documentation/docker.html'),
   ('pf.html', 'documentation/firewall-pf.html'),
   ('firewallsettings.html', 'documentation/firewall-settings.html'),
   ('firewalld.html', 'documentation/firewalld.html'),
   ('galeraparameters.html', 'documentation/galera-parameters.html'),
   ('galerastatusvariables.html', 'documentation/galera-status-variables.html'),
   ('glbparameters.html', 'documentation/glb-parameters.html'),
   ('glb.html', 'documentation/glb.html'),
   ('glossary.html', 'documentation/glossary.html'),
   ('haproxy.html', 'documentation/ha-proxy.html'),
   ('installmariadbsrc.html', 'documentation/install-mariadb-src.html'),
   ('installmariadb.html', 'documentation/install-mariadb.html'),
   ('installmysqlsrc.html', 'documentation/install-mysql-src.html'),
   ('installmysql.html', 'documentation/install-mysql.html'),
   ('installxtradbsrc.html', 'documentation/install-xtradb-src.html'),
   ('installxtradb.html', 'documentation/install-xtradb.html'),
   ('iptables.html', 'documentation/ip-tables.html'),
   ('isolationlevels.html', 'documentation/isolation-levels.html'),
   ('jails.html', 'documentation/jails.html'),
   ('legalnotice.html', 'documentation/legal-notice.html'),
   ('loadbalancing.html', 'documentation/load-balancing.html'),
   ('log.html', 'documentation/log.html'),
   ('managingfc.html', 'documentation/managing-fc.html'),
   ('migrate.html', 'documentation/migrate.html'),
   ('migration.html', 'documentation/migration.html'),
   ('monitor.html', 'documentation/monitor.html'),
   ('monitoringthecluster.html', 'documentation/monitoring-cluster.html'),
   ('mysqlwsrepfunctions.html', 'documentation/mysql-wsrep-functions.html'),
   ('mysqlwsrepoptions.html', 'documentation/mysql-wsrep-options.html'),
   ('mysqldump.html', 'documentation/mysqldump.html'),
   ('nodeprovisioning.html', 'documentation/node-provisioning.html'),
   ('nodestates.html', 'documentation/node-states.html'),
   ('notificationcmd.html', 'documentation/notification-cmd.html'),
   ('pcrecovery.html', 'documentation/pc-recovery.html'),
   ('pen.html', 'documentation/pen.html'),
   ('quorumreset.html', 'documentation/quorum-reset.html'),
   ('recovery.html', 'documentation/recovery.html'),
   ('reference.html', 'documentation/reference.html'),
   ('schemaupgrades.html', 'documentation/schema-upgrades.html'),
   ('scriptablesst.html', 'documentation/scriptable-sst.html'),
   ('security.html', 'documentation/security.html'),
   ('selinux.html', 'documentation/selinux.html'),
   ('sslcert.html', 'documentation/ssl-cert.html'),
   ('sslconfig.html', 'documentation/ssl-config.html'),
   ('sslsst.html', 'documentation/ssl-sst.html'),
   ('ssl.html', 'documentation/ssl.html'),
   ('sst.html', 'documentation/sst.html'),
   ('statetransfer.html', 'documentation/state-transfer.html'),
   ('streamingreplication.html', 'documentation/streaming-replication.html'),
   ('systemtables.html', 'documentation/system-tables.html'),
   ('introduction.html', 'documentation/tech-desc-introduction.html'),
   ('technicaldescription.html', 'documentation/technical-description.html'),
   ('upgrading.html', 'documentation/upgrading.html'),
   ('usingsr.html', 'documentation/using-sr.html'),
   ('versioninginformation.html', 'documentation/versioning-information.html'),
   ('weightedquorum.html', 'documentation/weighted-quorum.html'),
   ('xtrabackupoptions.html', 'documentation/xtrabackup-options.html')
 ]
